//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventories
    {
        public Inventories()
        {
            this.CS2Market = new HashSet<CS2Market>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ItemID { get; set; }
        public Nullable<double> Flot { get; set; }
        public int Count { get; set; }
    
        public virtual ICollection<CS2Market> CS2Market { get; set; }
        public virtual Items Items { get; set; }
        public virtual Users Users { get; set; }
    }
}
