//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.Inventories = new HashSet<Inventories>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> QualityID { get; set; }
        public decimal AveragePrice { get; set; }
        public string ItemPicture { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Inventories> Inventories { get; set; }
        public virtual Qualities Qualities { get; set; }
        public virtual Types Types { get; set; }
    }
}
