//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionsHistory
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int OperationID { get; set; }
        public decimal TransactionSum { get; set; }
        public System.DateTime DateOfTransaction { get; set; }
    
        public virtual Operations Operations { get; set; }
        public virtual Users Users { get; set; }
    }
}
