//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISIP123_Solodov_WPF
{
    using ISIP123_Solodov_WPF.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SteamMarketEntities : DbContext
    {
        public SteamMarketEntities()
            : base("name=SteamMarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CS2Market> CS2Market { get; set; }
        public DbSet<Inventories> Inventories { get; set; }
        public DbSet<Items> Items { get; set; }
        public DbSet<Iznos> Iznos { get; set; }
        public DbSet<Operations> Operations { get; set; }
        public DbSet<Qualities> Qualities { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TransactionsHistory> TransactionsHistory { get; set; }
        public DbSet<Types> Types { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
